name: 'Android application builder'
on:  push
jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: javavirys/android:30.0.3
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v1
